### ISSUE TITLE
Calvert Case Study - Client Phones (#4)

### ISSUE THREAD

**Issue by bcalvert531** [gloveboxhq/ams-data-cleaning-challenge#4]
The target data format wants 2 client phone numbers ("phone_number", "phone_number_2"). The client data file has 3 fields for phone number ("Phone_Cell", "Phone_Home", "Phone_Business"). Phone_Cell is slightly more populated than Phone_Home, and Phone_Business is all null. 

Based on this, I'm assuming that Phone_Cell should map to "phone_number" and Phone_Home should be "phone_number_2". Let me know if we have another preference.

**Comment by GloveBoxSean** [comment]
Great question. Often agencies we work with use multiple fields, so exactly what you just said is what we need to look for on the client data. We try to confirm what column has the best contact info… and a step further than that we want the Cell phone as the primary field.

So in this case you are correct.

**Comment by loganwillis** [comment]
Test Message here.
