### ISSUE TITLE
Calvert Case Study - Target Fields & Formats Assumptions

### ISSUE THREAD

**Issue by bcalvert531** [gloveboxhq/ams-data-cleaning-challenge#5]
@GloveBoxSean -- A couple quick questions/notes for you:

1) Target data format calls for column "ams_policy_status" -- my first assumption was that this was "Status" column, but that looks like it should end up as "active_inactive_status". Which field should be listed as "ams_policy_status"? My guess is "Transaction_Type_Code".

2) Target calls for "policy_division" -- What field should be used here? Assumption is "Line of Business".

3) The target data format document has email_2 far from email. I'm mirroring what's in that file since syntax is important, but want to confirm if this is correct or if it was an error in the target format file?

4) Instructions call to standardize the date fields -- assuming this means to typecast into OpenRefine's 'date' datatype.

**Comment by GloveBoxSean** [comment]
1: ‘ams_policy_status’ = ‘Transaction_type’
2: ‘policy_division’ = the department the policy lives in, so Personal, Commerical, life, etc. So for this particular set it is the ‘Policy_type’ column
3. Formatting of the email_2 - this does not matter, just so happened to be how this ended up. It is much easier to have this close to the ‘email’ column, however once the data is cleaned the location of the columns does not matter
4. Date fields - you are correct. You can use the Tranformation, to date within OpenRefine.
