### ISSUE TITLE
Clarification on ams_policy_type

### ISSUE THREAD

**Issue by ibrahimmudassar** [gloveboxhq/ams-data-cleaning-challenge#7]
I have everything done but I am having a hard time trying to cleanly map ams_policy_type for each policy. I even did glovebox_policy_type_id through a simple inference of LOB_Code but for the life of me I can't figure it out. 

@namrataglovebox

**Comment by namrataglovebox** [comment]
@ibrahimmudassar what is the problem you're running into specifically? Are you seeing all blanks or are a few things mapping?

**Comment by ibrahimmudassar** [comment]
@namrataglovebox I understand how to map glovebox id through LOB_code but I don't understand what to use to map asm

**Comment by namrataglovebox** [comment]
@ibrahimmudassar Ah I see. Remember that different agencies use different reports, so they come in differently. We want to normalize this into a format our system can ingest. We create some columns based on the data but also just need some data the agency sends us too. I hope this helps!
